services:

  message-service:
    build: ./notification-system/message-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

  postgres:
    image: postgres:16-alpine
    container_name: message_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_MESSAGE_DB}
      POSTGRES_USER: ${POSTGRES_MESSAGE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MESSAGE_PASSWORD}
    ports:
      - "5432:5432"

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.template.json:/etc/rabbitmq/definitions.template.json:ro
    command: >
      sh -c 'envsubst < /etc/rabbitmq/definitions.template.json
      > /etc/rabbitmq/definitions.json
      && rabbitmq-server'
      
volumes:
  rabbitmq: